#!/usr/bin/env bash
set -euo pipefail

warn() { echo 1>&2 "WARNING:" "$@"; }

####################################################################

export T8_PROJDIR=$(cd "$(dirname "$0")" && pwd -P)
t8dir=t8dev    # or whatever your submodule path is
[[ -r $T8_PROJDIR/$t8dir/t8setup.bash ]] \
    || git submodule update --init "$T8_PROJDIR/$t8dir"
. "$T8_PROJDIR"/$t8dir/t8setup.bash

t8dev="$T8_PROJDIR/t8dev/bin/t8dev"
cd "$T8_PROJDIR"

t8dev buildtoolset asl
t8dev buildtoolset ctools
t8dev buildtoolset cscp
t8dev buildtoolset RunCPM
t8dev aslt8dev
t8dev aslauto exe/ src/
(cd - && t8dev pytest -- "$@")  # Use original dir for relative cmd line params

#   PC-8001 Expansion ROM
pc8extmon=.build/obj/src/pc8extmon
p2bin -q -l 0 "$pc8extmon.p" "$pc8extmon.bin"
t8dev emulator cscp pc8001 n80=@7000:"$pc8extmon.bin"
