#!/usr/bin/env bash
set -euo pipefail

warn() { echo 1>&2 "WARNING:" "$@"; }

check_submodules() {
    count=$(git submodule status --recursive | sed -n -e '/^[^ ]/p' | wc -l)
    [ $count -eq 0 ] || {
        warn "$count Git submodules are not up to date"
        warn 'Run `git submodule update --init`?'
    }
}

####################################################################

export B8_PROJDIR=$(cd "$(dirname "$0")" && pwd -P)

cd "$B8_PROJDIR"
check_submodules
. ./pactivate -q
pip show t8dev 2>/dev/null \
    | grep -s '^Editable project location:' >/dev/null \
|| {
    echo "Installing editable r8format..."
    pip install -q -e t8dev
}

t8dev buildtoolset asl
t8dev aslauto exe/ src/
t8dev pytest -- "$@"
