#!/usr/bin/env bash
set -euo pipefail

warn() { echo 1>&2 "WARNING:" "$@"; }

####################################################################

export T8_PROJDIR=$(cd "$(dirname "$0")" && pwd -P)
t8dir=t8dev    # or whatever your submodule path is
[[ -r $T8_PROJDIR/$t8dir/t8setup.bash ]] \
    || git submodule update --init "$T8_PROJDIR/$t8dir"
. "$T8_PROJDIR"/$t8dir/t8setup.bash

t8dev="$T8_PROJDIR/t8dev/bin/t8dev"
cd "$T8_PROJDIR"

t8dev buildtoolset asl
t8dev aslauto exe/ src/
t8dev pytest -- "$@"
